import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { 
  ArrowLeft, Download, Share2, 
  Printer, MoreVertical, Clock,
  BookOpen, Sparkles, CheckCircle,
  AlertCircle, ChevronRight, FileText,
  Copy, Check
} from 'lucide-react';
import DashboardLayout from '../components/layout/DashboardLayout';
import useContentStore from '../store/contentStore';
import useCommunityStore from '../store/communityStore';

const ContentView = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { fetchContentById, loading } = useContentStore();
  const { createPost } = useCommunityStore();
  const [content, setContent] = useState(null);
  const [error, setError] = useState(null);
  const [isCopied, setIsCopied] = useState(false);
  const [isSharing, setIsSharing] = useState(false);

  const flattenAIContent = (data) => {
    if (!data) return "No content available.";
    if (typeof data === 'string') return data;
    
    // Handle structured objects (Notes, Reports, PPTs)
    let md = "";
    
    // Notes/Reports pattern: { sections: [{ title, content }] }
    if (data.sections && Array.isArray(data.sections)) {
        if (data.title) md += `# ${data.title}\n\n`;
        data.sections.forEach(s => {
            md += `## ${s.title}\n${s.content}\n\n`;
        });
        if (data.references && Array.isArray(data.references)) {
            md += `### References\n${data.references.map(r => `- ${r}`).join('\n')}\n`;
        }
    } 
    // PPT pattern: { slides: [{ title, content, notes }] }
    else if (data.slides && Array.isArray(data.slides)) {
        if (data.title) md += `# ${data.title}\n\n`;
        data.slides.forEach(s => {
            md += `---\n\n## Slide ${s.slideNumber}: ${s.title}\n${s.content}\n\n${s.notes ? `_Notes: ${s.notes}_` : ''}\n\n`;
        });
    }
    // Generic Object handling
    else {
        md = JSON.stringify(data, null, 2);
    }
    
    return md;
  };

  const mdContent = flattenAIContent(content?.content);

  useEffect(() => {
    if (id === 'temp-notes') {
        // Mocking for demo if no real id yet
        setContent({
            title: "Operating Systems: Process Management",
            topic: "Process States and Transitions",
            type: "notes",
            createdAt: new Date().toISOString(),
            content: `# Process Management in OS\n\n## Introduction\nA process is a program in execution. Process management involves various tasks like creation, scheduling, termination of processes, and a dead lock.\n\n### Process States\n1. **New**: The process is being created.\n2. **Ready**: The process is waiting to be assigned to a processor.\n3. **Running**: Instructions are being executed.\n4. **Waiting**: The process is waiting for some event to occur (such as an I/O completion or reception of a signal).\n5. **Terminated**: The process has finished execution.\n\n### Process Control Block (PCB)\nContains information about the process, including:\n- Process State\n- Program Counter\n- CPU Registers\n- CPU Scheduling Information\n- Memory-management information\n\n### Schedulers\n- **Long-term scheduler** (or job scheduler) – selects which processes should be brought into the ready queue.\n- **Short-term scheduler** (or CPU scheduler) – selects which process should be executed next and allocates CPU.\n- **Medium-term scheduler** – can be added if the degree of multiprogramming needs to be decreased.\n\n---
Generated by AcadBuddy AI v2.0`
        });
        return;
    }

    const loadContent = async () => {
      const data = await fetchContentById(id);
      if (data) setContent(data);
      else setError("Content not found or access denied.");
    };
    loadContent();
  }, [id]);

  const handleCopy = () => {
    navigator.clipboard.writeText(content.content);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleShare = async () => {
    setIsSharing(true);
    const result = await createPost({
        title: content.title,
        content: content.content,
        type: 'resource',
        metadata: {
            subject: content.subjectId?.name || "Academics",
            topic: content.topic,
            semester: 1 // Default or from user context
        }
    });
    if (result.success) {
        navigate('/community');
    }
    setIsSharing(false);
  };

  if (loading && !content) return (
    <DashboardLayout>
       <div className="h-[70vh] flex flex-col items-center justify-center space-y-6">
          <div className="w-16 h-16 relative">
             <div className="absolute inset-0 border-4 border-violet-500/20 rounded-full" />
             <div className="absolute inset-0 border-4 border-violet-500 border-t-transparent rounded-full animate-spin" />
          </div>
          <p className="text-xs font-black uppercase tracking-[0.3em] text-slate-500 animate-pulse">Parsing AI Output...</p>
       </div>
    </DashboardLayout>
  );

  if (error) return (
    <DashboardLayout>
       <div className="h-[70vh] flex flex-col items-center justify-center space-y-6 text-center">
          <div className="w-20 h-20 bg-rose-500/10 text-rose-500 rounded-3xl flex items-center justify-center mb-4">
             <AlertCircle size={40} />
          </div>
          <h2 className="text-2xl font-black text-gray-900 dark:text-white uppercase tracking-tight">{error}</h2>
          <button onClick={() => navigate(-1)} className="px-8 py-3 bg-violet-600 text-white font-black rounded-2xl shadow-xl">Go Back</button>
       </div>
    </DashboardLayout>
  );

  if (!content) return null;

  return (
    <DashboardLayout>
      <div className="max-w-5xl mx-auto pb-20">
        
        {/* ── Top Bar ── */}
        <section className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-10">
          <div className="space-y-1">
            <button 
              onClick={() => navigate(-1)}
              className="flex items-center gap-2 text-slate-500 hover:text-violet-500 transition-colors text-xs font-black uppercase tracking-widest mb-2"
            >
              <ArrowLeft size={16} /> Exit Reader
            </button>
            <h1 className="text-3xl font-black text-gray-900 dark:text-white tracking-tight">{content.title}</h1>
            <div className="flex items-center gap-3 text-[10px] text-slate-500 font-bold uppercase tracking-widest">
                <span className="flex items-center gap-1"><Clock size={12} /> {new Date(content.createdAt).toLocaleDateString()}</span>
                <span className="w-1 h-1 rounded-full bg-slate-300" />
                <span className="flex items-center gap-1 text-violet-500"><Sparkles size={12} /> AI Generated</span>
            </div>
          </div>

          <div className="flex items-center gap-3">
             <button 
               onClick={handleCopy}
               className="p-3 bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-2xl text-slate-600 dark:text-slate-400 hover:text-violet-500 transition-all flex items-center gap-2"
             >
                {isCopied ? <Check size={18} /> : <Copy size={18} />}
                <span className="text-xs font-black uppercase tracking-widest hidden sm:inline">{isCopied ? 'Copied' : 'Copy'}</span>
             </button>
             <button 
               onClick={handleShare}
               disabled={isSharing}
               className="p-3 bg-violet-600 text-white rounded-2xl shadow-lg shadow-violet-500/20 hover:scale-105 active:scale-95 transition-all flex items-center gap-2"
             >
                <Share2 size={18} />
                <span className="text-xs font-black uppercase tracking-widest hidden sm:inline">Share to Community</span>
             </button>
             <button className="p-3 bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-2xl text-slate-600 dark:text-slate-400 hover:text-rose-500 transition-all">
                <MoreVertical size={20} />
             </button>
          </div>
        </section>

        {/* ── Content Area ── */}
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-10">
           
           {/* Sidebar Info */}
           <div className="lg:col-span-1 space-y-8">
              <div className="bg-linear-to-br from-violet-500 to-indigo-600 rounded-4xl p-6 text-white shadow-xl shadow-violet-500/20 overflow-hidden relative">
                 <div className="absolute top-0 right-0 p-4 opacity-10">
                    <BookOpen size={64} />
                 </div>
                 <div className="relative z-10 space-y-4">
                    <h4 className="text-[10px] font-black uppercase tracking-[0.2em] opacity-70">Source Subject</h4>
                    <p className="text-lg font-black leading-tight">{content.subjectId?.name || "General Study"}</p>
                    <div className="h-px w-full bg-white/20" />
                    <div className="flex items-center justify-between text-[10px] font-bold uppercase opacity-80">
                       <span>Words</span>
                       <span>~{mdContent.split(/\s+/).length || 0}</span>
                    </div>
                    <div className="flex items-center justify-between text-[10px] font-bold uppercase opacity-80">
                       <span>Depth</span>
                       <span>Advanced</span>
                    </div>
                 </div>
              </div>

              <div className="space-y-4">
                 <h4 className="text-xs font-black text-slate-500 uppercase tracking-widest px-1">Quick Actions</h4>
                 <div className="grid grid-cols-1 gap-2">
                    {[
                        { label: 'Download PDF', icon: Download },
                        { label: 'Print Notes', icon: Printer },
                        { label: 'Cite Source', icon: Link },
                    ].map((btn, i) => (
                        <button key={i} className="flex items-center justify-between p-4 bg-white dark:bg-white/4 border border-gray-100 dark:border-white/8 rounded-2xl text-gray-700 dark:text-white hover:bg-gray-50 dark:hover:bg-white/8 transition-all group">
                           <div className="flex items-center gap-3">
                              <btn.icon size={18} className="text-slate-400 group-hover:text-violet-500" />
                              <span className="text-xs font-black uppercase tracking-widest">{btn.label}</span>
                           </div>
                           <ChevronRight size={14} className="opacity-0 group-hover:opacity-100 transition-opacity" />
                        </button>
                    ))}
                 </div>
              </div>
           </div>

           {/* Markdown Viewer */}
           <div className="lg:col-span-3">
              <motion.div 
                 initial={{ opacity: 0, y: 20 }}
                 animate={{ opacity: 1, y: 0 }}
                 className="bg-white dark:bg-white/2 border border-gray-100 dark:border-white/8 rounded-[48px] p-8 md:p-16 shadow-2xl shadow-black/5 dark:shadow-none min-h-150"
              >
                 <div className="prose prose-slate dark:prose-invert prose-violet max-w-none 
                   prose-headings:font-black prose-headings:tracking-tight
                   dark:prose-p:text-slate-300 dark:prose-li:text-slate-300
                   prose-p:leading-relaxed prose-li:leading-relaxed
                   prose-strong:text-violet-600 dark:prose-strong:text-violet-400">
              <div className="bg-slate-50 dark:bg-[#0b1020] border border-gray-100 dark:border-white/8 rounded-4xl p-8 md:p-12 shadow-inner shadow-black/5 dark:shadow-none">
                 <div className="prose prose-slate dark:prose-invert prose-violet max-w-none wrap-break-word
                   prose-headings:font-black prose-headings:tracking-tight prose-headings:text-gray-900 dark:prose-headings:text-white
                   prose-p:leading-relaxed prose-li:leading-relaxed
                   prose-p:text-slate-700 dark:prose-p:text-slate-300
                   prose-li:text-slate-700 dark:prose-li:text-slate-300
                   prose-strong:text-violet-700 dark:prose-strong:text-violet-400
                   prose-code:rounded-lg prose-code:bg-violet-500/10 prose-code:px-1.5 prose-code:py-0.5 prose-code:font-semibold
                   dark:prose-code:bg-white/10 dark:prose-code:text-violet-300
                   prose-pre:overflow-x-auto prose-pre:rounded-2xl prose-pre:border prose-pre:border-gray-200 prose-pre:bg-slate-900 prose-pre:text-slate-100
                   dark:prose-pre:border-white/10 dark:prose-pre:bg-black/40
                   prose-blockquote:border-l-violet-500 prose-blockquote:text-slate-600 dark:prose-blockquote:text-slate-300">
                    <ReactMarkdown>
                       {mdContent || "Generating AI content..."}
                    </ReactMarkdown>
                 </div>

                 {/* Footer metadata */}
                 <div className="mt-16 pt-8 border-t border-gray-100 dark:border-white/5 flex flex-col sm:flex-row items-center justify-between gap-4 text-[10px] font-bold text-slate-500 uppercase tracking-[0.2em]">
                    <div className="flex items-center gap-2">
                       <CheckCircle size={14} className="text-emerald-500" /> Accuracy Verified by AI Core
                    </div>
                    <div>AcadBuddy Content License v1.0</div>
                 </div>
              </motion.div>
           </div>
        </div>

      </div>
    </DashboardLayout>
  );
};

export default ContentView;